### DISCUSSION TITLE
Unhandled exception: Error during drmGetDevice for /dev/dri/renderD128, Invalid argument

### DISCUSSION THREAD

**Discussion by kaijuu189** [games-on-whales/wolf#205] [General]
docker compose

```yaml
version: "3"
services:
  wolf:
    image: 	gameonwhales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - WOLF_RENDER_NODE=/dev/dri/renderD128
      - WOLF_LOG_LEVEL=DEBUG
    volumes:
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host
    restart: unless-stopped
```

logs
[_wolf-wolf-1_logs (9).txt](https://github.com/user-attachments/files/20368294/_wolf-wolf-1_logs.9.txt)

```
[#@archlinux ~]$ ls -l /sys/class/drm/renderD*/device/driver
lrwxrwxrwx 1 root root 0 May 21 00:47 /sys/class/drm/renderD128/device/driver -> ../../../../bus/pci/drivers/nvidia
[#@archlinux ~]$ ls /dev/dri
by-path  card0  card1  renderD128
```
