### ISSUE TITLE
Steam container crashing after steam installation

### ISSUE THREAD

**Issue by moracabanas** [games-on-whales/wolf#106]
# Issue description
I follow docker instructions. Every APP is working but Steam.

It shows a black screen, then I press Shift and it show this view, **otherwise it remains at black screen**

![image](https://github.com/user-attachments/assets/8b11d406-c7da-485b-aeaf-dc87bfd6b4d9)

At this point here are the Steam container logs:

```log
[2024-08-30 04:12:28] 
[2024-08-30 04:12:28] [ /etc/cont-init.d/10-setup_user.sh: executing... ]
[2024-08-30 04:12:28] **** Configure default user ****
[2024-08-30 04:12:28] Setting default user uid=1000(retro) gid=1000(retro)
[2024-08-30 04:12:28] Setting umask to 000
[2024-08-30 04:12:28] Ensure retro home directory is writable
[2024-08-30 04:12:28] Ensure XDG_RUNTIME_DIR is writable
[2024-08-30 04:12:28] DONE
[2024-08-30 04:12:28] 
[2024-08-30 04:12:28] [ /etc/cont-init.d/15-setup_devices.sh: executing... ]
[2024-08-30 04:12:28] **** Configure devices ****
[2024-08-30 04:12:28] Exec device groups
[2024-08-30 04:12:28] Path '/dev/input/*' is not present.
[2024-08-30 04:12:28] Adding user 'retro' to groups: video,gow-gid-110,root
[2024-08-30 04:12:28] DONE
[2024-08-30 04:12:28] 
[2024-08-30 04:12:28] [ /etc/cont-init.d/30-nvidia.sh: executing... ]
[2024-08-30 04:12:28] 
[2024-08-30 04:12:28] 
[2024-08-30 04:12:28] [ /etc/cont-init.d/init-gamescope.sh: executing... ]
[2024-08-30 04:12:28] **** Setting up Gamescope ****
[2024-08-30 04:12:28] 
[2024-08-30 04:12:28] [ /etc/cont-init.d/system-services.sh: executing... ]
*** DBus started ***
*** Bluez started ***
bluetoothd[109]: Bluetooth daemon 5.70
bluetoothd[109]: src/adapter.c:adapter_init() Failed to access management interface
bluetoothd[109]: src/main.c:main() Adapter handling initialization failed
*** NetworkManager started ***
[2024-08-30 04:12:28] Launching the container's startup script as user 'retro'
[2024-08-30 04:12:28] Starting Steam with DISPLAY=
Warning: --icon-name is deprecated and will be removed in a future version of zenity; Treating as --icon.
(zenity:148): Gtk-WARNING **: 04:12:28.996: Unable to acquire session bus: Cannot autolaunch D-Bus without X11 $DISPLAY
libEGL warning: egl: failed to create dri2 screen
```

Then it installs like this 

![image](https://github.com/user-attachments/assets/130b23e1-1e50-4df3-8b86-6bb74a964087)

And it crashes after that inmediately.

Recurrent tries to open Steam from Moonlight client crashes Steam immediately with this.

![image](https://github.com/user-attachments/assets/ee9023af-5cdb-4299-a77c-d4191a381bc5)

There is no further logs available before crashing the Steam container.

I can reproduce from the ground up deleting `/etc/wolf/<number>/Steam` dir.

# Things I have tried:

- There is "/run/dbus" so a blind try was to add the mount to Steam launch config on `/etc/wolf/cfg/config.toml` like this (note **mounts=""/run/dbus..."**):

```toml
[[apps]]
start_virtual_compositor = true
title = "Steam"

[apps.runner]
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
"""
ports = []
devices = []
env = [
  "PROTON_LOG=1",
  "RUN_SWAY=true",
  "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
mounts = ["/run/dbus:/run/dbus"]
image = "ghcr.io/games-on-whales/steam:edge"
name = "WolfSteam"
type = "docker"
```
- I also tried `"Privileged: true"` but it doesn't work

No success. 

## Thoughts about this issue
I think there is something wrong with X11 in Popos so I cannot handle your compositor implementation without dummy HDMI plug or switching to Wayland(which I have no idea about) 

The thing is, Firefox, Pegasus, Retroarch and the Ball Test are working with sound.

# Further relevant info
### S.O
```
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy

```
## GPU Resources
- 2x Nvidia 3060 12Gb

## Nvidia Container CLI output
```
cli-version: 1.16.1
lib-version: 1.16.1
build date: 2024-07-23T14:57+00:00
build revision: 4c2494f16573b585788a42e9c7bee76ecd48c73d
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fplan9-extensions -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```

## Nvicia SMI output
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:0A:00.0 Off |                  N/A |
| 46%   29C    P8              6W /  170W |     145MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3060        Off |   00000000:0B:00.0 Off |                  N/A |
| 40%   27C    P8              7W /  170W |      18MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3514      G   /usr/lib/xorg/Xorg                              9MiB |
|    0   N/A  N/A      9313    C+G   ...libexec/gnome-remote-desktop-daemon        104MiB |
|    0   N/A  N/A      9466      G   /usr/bin/gnome-shell                            3MiB |
|    1   N/A  N/A      3514      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
```

Thanks you for this impressive piece of software.

Regards

**Comment by salty2011** [comment]
Hey @moracabanas

Interesting issue you are getting. Could you also attach the docker compose config for reference. Thanks for providing all the other information.

Additionally i noticed the in the config.toml the steam container you are using is "ghcr.io/games-on-whales/steam:edge",

Have been chatting on the discord about this issue, the screen shots / logs you have posted indicate that the container doesn't start sway. Just to rule things out, on the host can you try pulling the steam image again using

`docker pull ghcr.io/games-on-whales/steam:edge
`

**Comment by moracabanas** [comment]
Thanks for the suggestion I'm trying it out rn

Here is my `docker-compose.yml` 


```yaml
version: "3"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - WOLF_RENDER_NODE=/dev/dri/renderD129
      - WOLF_LOG_LEVEL=DEBUG


    volumes:
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia

              capabilities: [gpu]
    # network_mode: host
    ports:
      - "47984:47984/tcp"  # HTTPS
      - "47989:47989/tcp"  # HTTP
      - "47999:47999/udp"  # Control
      - "48010:48010/tcp"  # RTSP
      - "48100-48110:48100-48110/udp"  # Video (up to 10 users)
      - "48200-48210:48200-48210/udp"  # Audio (up to 10 users)
    restart: unless-stopped
```

Because I am running a LLM on GPU0, I am trying to select GPU1 by forcing `D129` rendering node selection, and I tested it working on firefox by checking `nvidia-smi`  usage.   


PD: While I am not proficent, I "speak fluent Docker"
