### ISSUE TITLE
How to properly enable GPU when device is iommu?

### ISSUE THREAD

**Issue by futurepr0n** [games-on-whales/wolf#128]
Trying to run as a proxmox, started by creating a container and then installing using a combo of the dockerfile and docker-compose.yml I created. I didn't have /dev/dri, so I mapped as iommu - maybe thats my issue. But righ now heres how it looks and my crash info.

  GNU nano 7.2                                                                                          docker-compose.yml                                                                                                    
```
version: "3"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
    volumes:
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /mnt/udev:/run/udev:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/iommu
      - /dev/uinput
      - /dev/uhid
    network_mode: host
    restart: unless-stopped


```
  
GNU nano 7.2                                                                                              Dockerfile                  
```                                                                                 
# HTTPS
EXPOSE 47984/tcp
# HTTP
EXPOSE 47989/tcp
# Control
EXPOSE 47999/udp
# RTSP
EXPOSE 48010/tcp
# Video (up to 10 users, you can open more ports if needed)
EXPOSE 48100-48110/udp
# Audio (up to 10 users, you can open more ports if needed)
EXPOSE 48200-48210/udp
```

my LXC.conf
```
arch: amd64
cores: 12
dev0: /dev/uinput
dev1: /dev/uhid
dev2: /dev/iommu
features: nesting=1
hostname: wolf
memory: 8192
net0: name=eth0,bridge=vmbr0,hwaddr=BC:24:11:CC:A7:93,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-141-disk-0,size=22G
swap: 512
tags: proxmox-helper-scripts
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.mount.entry: /dev/iommu dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/input dev/input none bind,optional,create=dir
lxc.mount.entry: /run/udev mnt/udev none bind,optional,create=dir
```

Things crashed after i set the pin and connected the server successfully.

![Screenshot 2024-09-26 at 11 43 13 PM](https://github.com/user-attachments/assets/14b00019-2686-4299-b406-c69f521ae68c)
![Screenshot 2024-09-26 at 11 44 36 PM](https://github.com/user-attachments/assets/e1669326-6508-47e0-ba2f-e22f96248b66)

If I run screenfetch on the container, i can see things look ok, same with lspci
![Screenshot 2024-09-26 at 11 49 56 PM](https://github.com/user-attachments/assets/1f396a49-1f7a-4c5f-8ad2-d6c85e10b117)
