### ISSUE TITLE
No video recieved from host

### ISSUE THREAD

**Issue by ankit2951** [games-on-whales/wolf#175]
Trying to use this in my local network but I keep on getting this error when opening Steam.

![Image](https://github.com/user-attachments/assets/e6df3e71-5b8e-45ec-bac7-797904f1804f)

`ERROR | [GSTREAMER] Pipeline error: Failed to connect stream: No such entity`

Here is my compose file
```
version: "3"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
    volumes:
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - c 13:* rmw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    network_mode: host
    restart: unless-stopped
networks: {}
```
