### ISSUE TITLE
Sound not working with Moonlight UWP anymore

### ISSUE THREAD

**Issue by nilleiz** [games-on-whales/wolf#201]
Hello!

I was already using Wolf + Steam successfully on Xbos Series X.
Without any update installed on the Xbox the audio stopped working with Wolf on all applications.

See full logs I attached at the end of the post.
The sound is not working in any configuration (Stereo, 5.1, 7.1)

I am using Nvidia-Toolkit on Ubuntu Server 24.04.2

Docker Version: 

```
Client: Docker Engine - Community
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:41:31 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.11
  Git commit:       4c9b3b0
  Built:            Wed Jan 22 13:41:31 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
nvidia-smi
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050        Off | 00000000:13:00.0 Off |                  N/A |
| 30%   28C    P8              N/A / 115W |      4MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
```

Docker-Compose:

```
version: "3"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/mnt/cachessd/wolf
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/cachessd/wolf/:/mnt/cachessd/wolf/
      - /mnt/cachessd/wolf/:/etc/wolf/
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      macvlan:
        ipv4_address: 192.168.0.134
    restart: unless-stopped

networks:
  macvlan:
    external: true
```

Logs:
[WolfPulseAudio_logs.txt](https://github.com/user-attachments/files/20209426/WolfPulseAudio_logs.txt)
[wolf-wolf-1_logs.txt](https://github.com/user-attachments/files/20209424/wolf-wolf-1_logs.txt)
[WolfSteam_7926182639981431385_logs.txt](https://github.com/user-attachments/files/20209425/WolfSteam_7926182639981431385_logs.txt)

Moonlight UWP settings:

![Image](https://github.com/user-attachments/assets/3eefd2b0-bdbe-4afe-a87d-50db720efad2)
