### ISSUE TITLE
WOLF_INTERNAL_IP is not used for mDNS?

### ISSUE THREAD

**Issue by shawly** [games-on-whales/wolf#216]
Hi again,

I'm using a docker macvlan network to expose certain containers to my home subnet (br0). Before my wolf_default network was mapped to br0.
When I started using wolfmanager I changed the default: network to be internal so that wolfmanager will get its own internal ip in the wolf_default network, as I don't want it to assign to an IP in my home subnet.

The problem now is, that wolf also is in the default network now and not only in the br0 network. So mDNS will report the docker networks ip 172.26.0.3 for wolf instead of 192.168.10.140.
I found in the code that there is an env var for WOLF_INTERNAL_IP, but it seems that the ip isn't used for mDNS.

Here is my compose file:

```yaml
services:                                                                                                                                                                                                                                                                                                                   
  app:                                                                                                                                                                                                                                                                                                                      
    restart: always                                                                                                                                                                                                                                                                                                         
    environment:                                                                                                                                                                                                                                                                                                            
      TZ: Europe/Berlin                                                                                                                                                                                                                                                                                                     
      XDG_RUNTIME_DIR: /tmp/sockets                                                                                                                                                                                                                                                                                         
      HOST_APPS_STATE_FOLDER: /srv/wolf/data                                                                                                                                                                                                                                                                                
      WOLF_CFG_FILE: /srv/wolf/data/cfg/config.toml                                                                                                                                                                                                                                                                         
      WOLF_CFG_FOLDER: /srv/wolf/data/cfg                                                                                                                                                                                                                                                                                   
      WOLF_PRIVATE_CERT_FILE: /srv/wolf/data/cfg/cert.pem                                                                                                                                                                                                                                                                   
      WOLF_PRIVATE_KEY_FILE: /srv/wolf/data/cfg/key.pem
      WOLF_DOCKER_SOCKET: /var/run/docker.sock
      WOLF_LOG_LEVEL: INFO
      WOLF_SOCKET_PATH: /var/run/wolf/wolf.sock
      WOLF_INTERNAL_IP: 192.168.10.140
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
    - /srv/wolf/data:/srv/wolf/data
    - /tmp/sockets:/tmp/sockets:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/run/wolf:/var/run/wolf
    - /dev/:/dev/:rw
    - /run/udev:/run/udev:rw
    image: ghcr.io/games-on-whales/wolf:stable
    container_name: wolf
    device_cgroup_rules:
    - c 13:* rmw
    devices:
    - /dev/dri
    - /dev/uinput
    - /dev/uhid
    networks:
      default:
      br0:
        ipv4_address: 192.168.10.140

  web:
    restart: always
    environment:
      TZ: Europe/Berlin
      NODE_ENV: production
      NEXTAUTH_SECRET: xxx
      ENCRYPTION_KEY: xxx
      NEXTAUTH_URL: https://wolf.example.com
      NEXTAUTH_TRUST_HOST: 'true'
      AUTH_TRUST_HOST: 'true'
    labels:
      traefik.enable: true
      traefik.http.routers.wolf-http.service: wolf
      traefik.http.routers.wolf-http.entrypoints: web
      traefik.http.routers.wolf-http.rule: Host(`wolf.example.com`)
      traefik.http.routers.wolf.service: wolf
      traefik.http.routers.wolf.entrypoints: web-secure
      traefik.http.routers.wolf.middlewares: secHeaders@file
      traefik.http.routers.wolf.rule: Host(`wolf.example.com`)
      traefik.http.routers.wolf.tls: true
      traefik.http.routers.wolf.tls.certresolver: default
      traefik.http.services.wolf.loadbalancer.server.port: 3000
    volumes:
    - /var/run/wolf:/var/run/wolf
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /srv/wolf/webconfig:/app/config
    - /srv/wolf/webdata:/app/data
    image: ghcr.io/games-on-whales/wolfmanager/wolfmanager:latest
    container_name: wolf-manager
    depends_on:
    - app
    networks:
      default:
      traefik_net:

networks:
  default:
  traefik_net:
    external: true
  br0:
    external: true
    name: br0
```
