### ISSUE TITLE
New Steam Game Pad UI (Steam Deck) Prevents Proper Setup

### ISSUE THREAD

**Issue by a-priestley** [games-on-whales/wolf#38]
The UI falsely displays network scanning errors during setup. This causes the inability to properly set up Steam.

Possibly related, the UI shows the following exception:
![image](https://github.com/games-on-whales/wolf/assets/47989725/d14ba4cc-b44a-4bf9-a682-0a0ca4fd230f)

One workaround is to use the normal desktop UI initially to log into Steam by setting the startup flag `-nogamepadui`. Example section in `config.toml`:

```toml
 [[apps]]
title = "Steam"
start_virtual_compositor = true

[apps.runner]
type = "docker"
name = "WolfSteam"
image = "ghcr.io/games-on-whales/steam:edge"
mounts = ["/run/udev:/run/udev:ro"]
env = [
"STEAM_STARTUP_FLAGS=-nogamepadui","PROTON_LOG=1","RUN_GAMESCOPE=true","GOW_REQUIRED_DEVICES=/dev/uinput /dev/input/event* /dev/dri/* /dev/nvidia*",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["SYS_ADMIN", "SYS_NICE"],
    "Privileged": false
  }
}
\
"""
```

After logging in, Steam can continue to be used with the flag omitted if desired.
