### ISSUE TITLE
Custom Resolutions causing screen corrumption

### ISSUE THREAD

**Issue by brine0m** [games-on-whales/wolf#41]
If you set a custom resolution in Moonlight and then connect to the Wolf server all applications output a corrupted screen.

**Steps to reproduce**
In the moonlight client set a custom resolution and then connect to any application presented in Wolf

**screenshot**
![image](https://github.com/games-on-whales/wolf/assets/77773699/2a89c4b6-2f3e-43f4-95e1-0bfb4ab2368d)

**HARDWARE**
- AMD 7900 XTX
- AMD Ryzen

**LOGS**
Here are the logs I have for the container
[wolf-wolf-1_logs.txt](https://github.com/games-on-whales/wolf/files/12556993/wolf-wolf-1_logs.txt)

Some additional output captured while troubleshooting
rror: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 23.0.2 for AMD Radeon Graphics (gfx1100, LLVM 15.0.7, DRM 3.52, 6.4.10-202.fsync.fc38.x86_64)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

**Comment by salty2011** [comment]
Curious any leads on this issue or additional information required. Was going to give Wolf another spin over the weekend and try and debug this issue.

**Comment by ABeltramo** [comment]
Lots have changed since this was open. The good news is that nobody has reported anything like this lately, so I guess it's good. I'll make sure to double-check it once I've got my Intel ARC GPU setup!

**Comment by salty2011** [comment]
hey @ABeltramo, just did some testing. it looks like any resolution that default in the moonlight client (eg 1080p,1440p) all appear to work without issue. 4k resolution doesn't get corrupted but it does freeze once the steam bigpicture is and the main screen. For reference this is with a AMD 6900XT.

When setting a custom resolution, in this case 3440x1440 at 60fps with or without vsync or frame pacing still getting corrupted screen. have attached screenshot and debug logs.

![image](https://github.com/user-attachments/assets/ebbb7103-daa4-442a-a6bf-fea128a0c425)
[wolf_3440x1440_debug.txt](https://github.com/user-attachments/files/16319159/wolf_3440x1440_debug.txt)

**Comment by ABeltramo** [comment]
Thanks for testing it out, I'll check it out soon-ish

**Comment by salty2011** [comment]
cool np, let me know if you need any additional logs or need me to doing else to help, this running on a test rig so can easily test.

**Comment by erenatas** [comment]
Hi, I can reproduce this issue, trying a 4:3 resolution gives the same result. Same GPU with @brine0m , also let me know if there is anything I can do for logs, testing, etc.

**Comment by salty2011** [comment]
@erenatas as a starting point might be worth enabling debug logging for wolf, replicating the issue and attaching the logs like I have. At least now with someone else getting the same issue on an AMD card its less likely a weird config issue I have done.  Also might be worth noting the specific resolution you tried. in my case its an ultra wide using resolutions of 3440x1440, although in testing I found any custom resolutions not already listed in the moonlight client appeared to have problems.

Just to add, have also tried just straight Sunshine on a computer and then doing custom resolutions. No issue when doing that.

**Comment by ABeltramo** [comment]
I've lightly tested this on my Intel ARC A380 using https://github.com/games-on-whales/wolf/pull/91 (you can pull it using `ghcr.io/games-on-whales/wolf:dev-multi-gpu`) and I can't reproduce the issue when using any of the provided encoders: `vaapi`, `qsv` (and `nvcodec` too on my Nvidia GPU) all seems to handle both `1024x768`
![Screenshot 2024-08-06 at 20 15 06](https://github.com/user-attachments/assets/0881b059-171d-4b3b-a9ae-733302e04b0d)

and `3440x1440`
![Screenshot 2024-08-06 at 20 13 44](https://github.com/user-attachments/assets/afcb74e4-5ec6-4243-a0e6-6afeb4b17472)

when using Moonlight-QT on OSX as the client.

Could you guys try out the latest version on that branch?

**Comment by salty2011** [comment]
hey @ABeltramo , was just looking at what are the version on the container registry for wolf. I currently using the stable tag, didnt see a latest tag to check out?  This is the list I am seeing currently

![image](https://github.com/user-attachments/assets/3642dd1c-fce5-4e08-aed3-1cf8cc4e2845)

**Comment by salty2011** [comment]
I went ahead of switched my wolf container to a tag that was from the last day.

For reference
**Client Details**
Moonlight Windows: 6.0.1
Windows 11

**Host**
GPU: 6900XTX
Wolf Ver: sha-1c3556f
HostOS: Unraid 6.12.11 with RadeonTOP

Docker Compose
```
version: "3.8"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:sha-1c3556f
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/mnt/cache/appdata/wolf/apps
      - WOLF_CFG_FILE=/mnt/cache/appdata/wolf/cfg/config.toml
      - WOLF_PRIVATE_KEY_FILE=/mnt/cache/appdata/wolf/cfg/key.pem
      - WOLF_PRIVATE_CERT_FILE=/mnt/cache/appdata/wolf/cfg/cert.pem
      - WOLF_LOG_LEVEL=DEBUG
      - WOLF_RENDER_NODE=/dev/dri/renderD129
    volumes:
      - /mnt/cache/appdata/wolf:/mnt/cache/appdata/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri/renderD129
      - /dev/dri/card1
      - /dev/uinput
    network_mode: host
    restart: unless-stopped
```

Because I have several GPU's have explicitly set the GPU to use and have updated config/toml to correctly use renderD129

I have attached the logs that includes both tests:
Log: "[wolfbuild_sha-1c3556f_20240708.txt](https://github.com/user-attachments/files/16517949/wolfbuild_sha-1c3556f_20240708.txt)"

- Launched steam app using 1440p @ 100fps. Working with no issues
- Launched steam app using 3440x1440 @60fps, Not Working, getting screen corruption but do hear the start sound for steam bigpicture and controls seem to also work, see screen shot

![image](https://github.com/user-attachments/assets/7494492b-9063-48f1-aa95-e76bc9655a4f)

Out of interest I also then proceeded to do the same test using 1024x768@60fps, this works no issues
![image](https://github.com/user-attachments/assets/c53188ef-77bd-455e-95d0-a927c5ef5f53)

given that wasn't an ultrawide resolution i then tried the following resolutions which are all ultra-wide. format is RES - ASPECT - FPS > Result

2560x1080 - 64:27 - 60fps > Working
2880x1200 - 12:5 - 60fps > Working
2880x1440 - NotSure - 60fps > Working
3440x1080 - NotSure - 60fps > Screen corrupted:
3440x1440 -  34:18 - 60fps > Screen corrupted:
4320x1800 - 12:5 - 60fps > Black screen, hear start sound before client stops abruptly with error "No video from host
5120x1440 - 32:9 - 60fps > Black screen, hear start sound before client stops abruptly with error "No video from host

Based on this testing it would seem once the horizontal gets above 2880 the issue appears to occur for AMD cards.
