### ISSUE TITLE
Steam cannot switch to Desktop

### ISSUE THREAD

**Issue by rty813** [games-on-whales/wolf#75]
I want to add Non-steam game to library, so I need to switch to desktop. But it stuck.

![6b3b198eb9a32ee86433364e122df7f](https://github.com/games-on-whales/wolf/assets/22488813/c18de0a7-e454-4cc6-9339-b50d077d7008)

**Comment by ABeltramo** [comment]
This should work on the latest Steam image when using `Sway` instead of `Gamescope`. You can try it out by pulling the latest image:
```bash
docker pull ghcr.io/games-on-whales/steam:edge
```
and setting in `config.toml`
```toml
env = [
  "RUN_SWAY=true",
  "PROTON_LOG=1",
  "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
```
under the `Steam` entry
